name: pokeapi
description: PokeAPI Package
version: 1.0.4
homepage: "https://github.com/prathanbomb/pokedart"

environment:
    sdk: '>=2.14.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: ^1.17.10
